### ISSUE TITLE
If you're looking for a newer version of MEGAsync on Void, check this out

### ISSUE THREAD

**Issue by loukamb** [ibhagwan/megasync-template#2]
_(this is for people that end up here while looking for MEGAsync on Void, like I did, but didn't want to install this due to the antiquated version)_

I've made an updated template for MEGAsync [here](https://github.com/loukamb/void-packages). It doesn't compile the package locally, relying instead on the Debian binary distributed by the platform (which also rolls in all dependencies). To install it, install `xtools` (`xbps-install -S xtools`) and just run the following the commands:

```sh
# Clone the repository.
git clone https://github.com/loukamb/void-packages

# Cd into the repository.
cd void-packages

# Bootstrap the environment.
./xbps-src binary-bootstrap

# Build megasync.
./xbps-src pkg megasync

# Install megasync.
xi megasync
```

I've already asked on the Void Linux whether I should PR this to void-packages but I was told that they're not adding anymore restricted packages.

**Comment by loukamb** [comment]
FYI the repository has recently updated to 5.2.1.0, which is good news, but my fork of void-packages allows you to install 5.6.0.0 currently. Just letting you know.

**Comment by loukamb** [comment]
Updated to 5.6.1.

**Comment by KF-Art** [comment]
Additionally, if for some reason you want/need to compile it yourself, I've made a new [template](https://codeberg.org/cereus-linux/cereus-pkgs/src/branch/master/srcpkgs/megasync) at [cereus-pkgs](https://codeberg.org/cereus-linux/cereus-pkgs), based on this and AUR.

**Comment by ibhagwan** [comment]
> Additionally, if for some reason you want/need to compile it yourself, I've made a new [template](https://codeberg.org/cereus-linux/cereus-pkgs/src/branch/master/srcpkgs/megasync) at [cereus-pkgs](https://codeberg.org/cereus-linux/cereus-pkgs), based on this and AUR.

Ty @KF-Art, I’ve based this package on https://aur.archlinux.org/packages/megasync-nopdfium, which AUR package are you referring too?

I also prefer compiling than using prebuilt binaries, if this makes sense and you want we can PR your changes.

**Comment by KF-Art** [comment]
> > Additionally, if for some reason you want/need to compile it yourself, I've made a new [template](https://codeberg.org/cereus-linux/cereus-pkgs/src/branch/master/srcpkgs/megasync) at [cereus-pkgs](https://codeberg.org/cereus-linux/cereus-pkgs), based on this and AUR.
> 
> Ty @KF-Art, I’ve based this package on https://aur.archlinux.org/packages/megasync-nopdfium, which AUR package are you referring too?
> 
> I also prefer compiling than using prebuilt binaries, if this makes sense and you want we can PR your changes.

Oh, I wasn't aware that there were an specific AUR package that removes libpdfium. In my case I took reference from the normal [megasync](https://aur.archlinux.org/packages/megasync) package and added `-DUSE_PDFIUM=OFF` in `configure_args`. The package you mentioned seems to be outdated and maybe those sed commands are no longer required after the CMake transition MEGAsync made. I'll be looking further on this as soon as I have time.

Well, I could make a PR if you would like to, so you don't need to clone the entire `cereus-pkgs` repo to build this (although I recommend giving it a look since we package many extra stuff there). Updates would come here in form of PR after commiting in cereus-pkgs, ofc.

**Comment by ibhagwan** [comment]
> Oh, I wasn't aware that there were a specific AUR package that removes libpdfium. In my case I took reference from the normal [megasync](https://aur.archlinux.org/packages/megasync) package and added -DUSE_PDFIUM=OFF in configure_args. The package you mentioned seems to be outdated and maybe those sed commands are no longer required after the CMake transition MEGAsync made. I'll be looking further on this as soon as I have time.

TBH, I did this long ago and can’t recall why I chose this specific AUR but there had to have been a reason, I don’t even know what pdfium is :)

I also had no idea about the cmake transition, I don’t use this package much and wasn’t following the development.

> Well, I could make a PR if you would like to, so you don't need to clone the entire cereus-pkgs repo to build this (although I recommend giving it a look since we package many extra stuff there). Updates would come here in form of PR after commiting in cereus-pkgs, ofc.

Thar would be great, Ty @KF-Art!

**Comment by KF-Art** [comment]
Alright, I've made a PR at #3. Feel free to review it.
Sorry for the delay, I've been busy lately.

**Comment by KF-Art** [comment]
> TBH, I did this long ago and can’t recall why I chose this specific AUR but there had to have been a reason

It likely has to do with the fact pdfium isn't packaged in Void repositories as of now.

**Comment by ibhagwan** [comment]
> Alright, I've made a PR at https://github.com/ibhagwan/megasync-template/pull/3. Feel free to review it.
> Sorry for the delay, I've been busy lately.

Thank you very much @KF-Art, for this great help as I'm far from an expert in xbps-src.

> It likely has to do with the fact pdfium isn't packaged in Void repositories as of now.

Probably, it's been so long,  I just wanted something that worked :-)

Closing this issue as no longer relevant.
